### ISSUE TITLE
Question about images

### ISSUE THREAD

**Issue by khwerhahn** [victorsteven/React-Client-That-Consumes-Fullstack-Gin-API#1]
Hi,

thanks for the great boilerplate. I'm getting into React and this really helps. 

I'm somewhat confused about the images. They 'src' seems to get encoded. For example in the Posts.js. I have added under Assets some images of my own, but they are not found. Is this some Webpack thing? Sorry for the beginner question.

**Comment by khwerhahn** [comment]
Solved....

**Comment by victorsteven** [comment]
Oh, great. Sorry for the late response.
